### ISSUE TITLE
variables to resources

### ISSUE THREAD

**Issue by Rolograaf** [DanteCoder/JoplinPluginNoteVariables#16]
Was hoping this plugin would define me variables to resources, but it will render the link-reference instead displaying link itself.

For example -- I have some images in this case SVG of the flag of Monaco (it came from webclipping a website) and made it a resource in my Joplin dBase:
`![Monaco](https://cdn-1.motorsport.com/static/img/cf/mc-2.svg)` => `![Monaco.svg](:/aed8a6dec36e44c184e53dde8a1febca)`

Then I put it in the variable table

```markdown
| variable | value |
| -------- | ----- |
| !monaco | ![Monaco.svg](:/aed8a6dec36e44c184e53dde8a1febca) |
```

Hoping to use `!monaco` everywhere in Joplin to get the flag, 

![Monaco](https://cdn-1.motorsport.com/static/img/cf/mc-2.svg)

but it will just give me `![Monaco.svg](:/aed8a6dec36e44c184e53dde8a1febca)` in the text

Is there anyway I could use this variables-plugin in my use-case?

**Comment by DanteCoder** [comment]
Right now this plugin only works replacing pure text, this is because of how the markdown processor works.
Maybe there's a way around this but I'm not sure.
