### ISSUE TITLE
Feature request: JSON syntax highlighting

### ISSUE THREAD

**Issue by xardbaiz** [DanteCoder/JoplinPluginNoteVariables#3]
Hello. Thanks for your work. As a small tweak could you please add opportunity to store variables with JSON syntax highlighting. Because current output (right side) doesn't comfort for eyes

Current:
![image](https://user-images.githubusercontent.com/92844117/148903974-8a66f7fb-d5dd-42d4-9165-74c0298a7160.png)

Desired:
![image](https://user-images.githubusercontent.com/92844117/148904049-fba1c4e6-623e-4ee9-a4a5-eca8ea12d29c.png)

**Comment by DanteCoder** [comment]
Ok, I'll look into it.
Thanks for the suggestion!

**Comment by DanteCoder** [comment]
Updated to v2.0.0. Variables Notes are no longer in JSON format but in Markdown table format.
