### ISSUE TITLE
can we set css styles as a variable?

### ISSUE THREAD

**Issue by mohammadmohammadiarchangel** [DanteCoder/JoplinPluginNoteVariables#4]
I need to set CSS styles as a variable. For example && for the color blue style and $$$ for the color blue and bold together or another color. I mean when I type $$word$$ I expect it will write in blue. And I want to define $$ as a variable for blue.

**Comment by DanteCoder** [comment]
Try changing the default "%" delimiter with something else that doesn't has the symbols you are using as your variables.
I would try double dash "__", but you can choose anything.
