### ISSUE TITLE
What I miss

### ISSUE THREAD

**Issue by sergioflorespereira** [DanteCoder/JoplinPluginNoteVariables#6]
Hi this is a very interesting plug-in, with lots of potential. If I may make the following suggestions - I would be very grateful.

1. The area where one adds variables ... scrolls down as one adds variables and then becomes unseen when there are too many. Could it not rather be at the top and variables are add below it ?
2. Could the variables list have a scroll bar so one can go down the list and change values with out going into the %NoteVariables% file ? (the %NoteVariables% file is too confusing for a non programmer like me)
3. This may be asking too much, but this plug in is very useful for different types of notes / documents, so if at the beginning of a note or document one could refer to a specific: %NoteVariables - XXX%, then different files could have %NoteVariables% ... this would save time.

Thank you very much for your attention and time -much appreciated.
Sergio

**Comment by DanteCoder** [comment]
Points 1 and 2: I removed the right panel on v2.0.0, now the variables can be edited directly on the Variables Note using the Markdown table format, please update to the latest version and check the [Usage](https://github.com/DanteCoder/JoplinPluginNoteVariables#usage).
Point 3 is now implemented on v2.0.0 ;)

**Comment by sergioflorespereira** [comment]
Thank you !
Can't wait to try it out !!
Best regards,
Sérgio
