### ISSUE TITLE
Infinite "Updated remote items: 1"

### ISSUE THREAD

**Issue by sif** [DanteCoder/JoplinPluginNoteVariables#7]
Hello, this is a great plugin and I hope we can get more development on it. 

Here is how I have been able to reproduce this bug:
1. It seems that after I install the plugin and use it, I hit "Synchronize".
2. Joplin tells me it is updating. I hit it again after it completes.
3. It tells me it is updating.
4. You can repeat step 2.

Current "fix" is to uninstall the plugin. Joplin behaves as expected when this plugin is not installed.

Expected behavior: seeing a "Completed: " after the sync process.

**Comment by DanteCoder** [comment]
Thank you for pointing out that.
I've left this plugin a bit because of work, but I'll take that into account after I give some time to the plugin.

**Comment by DanteCoder** [comment]
I updated the plugin to 2.0.0, let me know if you have the same issue.

**Comment by sif** [comment]
I just reinstalled it but now do not see a way to manage the variables. It looks like it moved to the Note menu, so I hit "Create variables note". It seems to work, no more infinite loop. 

I think I like the new way more but I have a question. The import is so that you can import multiple pages right? The previous version could not do that?

Anyway, good to close.

**Comment by DanteCoder** [comment]
Yeah, the new version has this feature to import multiple notes. The previous version just had a single note where all the variables were stored.
