### ISSUE TITLE
Conflict with the Outline plugin

### ISSUE THREAD

**Issue by petzi53** [DanteCoder/JoplinPluginNoteVariables#8]
Installing your plugin destroys the functionality of the [Outline plugin](https://github.com/cqroot/joplin-outline). The Outline plugin loses its functionality to toggle the visibility of the panel: The outline button (hamburger icon) disappears, and the shortcut F9 does not work anymore.

**Comment by DanteCoder** [comment]
@petzi53 Thank you for the feedback, I'm working on an update

**Comment by DanteCoder** [comment]
I updated the plugin to 2.0.0, please let me know if you still have this issue with the new version.

**Comment by petzi53** [comment]
Yep! (I now believe anyway that the problem is more related to the Outline plugin, as I have noticed conflicts with other plugins as well.)

I noticed that you changed the UI and how to use the plugin. It seems now easier to handle. But has the user to import the variables for each note, as it currently works? That would defy the whole idea of your plugin: time-saving with typing.

**Comment by sif** [comment]
Perhaps an idea that could work is that there is a default global variable page. One that does not need to be imported.

**Comment by DanteCoder** [comment]
I'm closing the original issue.

> Perhaps an idea that could work is that there is a default global variable page. One that does not need to be imported.
I'll take into account that for the next version. If you have any more ideas for that please open a new issue.
